### ISSUE TITLE
Make DAGs accessible to airflow workers

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#11]
As the Airflow UI does not offer the possibiity to design or load DAGs, these will have to be made available to airflow by other means, e.g. by including them in the docker image, mounting them or pulling them from a repository:

https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html?highlight=git#managing-dags-and-logs

This is done when
- [ ] an approach has been chosen (PV/ConfigMap/sth. different)
- [ ] CRD changes have been proposed and reviewed at the architecture meeting
- [ ] the reviewed changes have been implemented so I can add DAGs to Airflow
- [ ] documentation, examples and integration tests have been added/updated

I have one unknown: Can new DAGs be added on-the-fly? And if not what do we do?

**Comment by lfrancke** [comment]
I would suggest to start with what was mentioned: Add them via a ConfigMap for now.

This will not allow all scenarios (e.g. external dependencies/pip/virtualenv stuff) but is a good and easy start.

@soenkeliebau / @adwk67 opinions?

**Comment by soenkeliebau** [comment]
I don't have a strong preference on PV vs ConfigMap tbh. In the operator it makes as near as no difference I think.

**Comment by lfrancke** [comment]
Okay, thank you.
Either way is fine for me.
