### ISSUE TITLE
Implement resource requests and limits for Airflow pods

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/airflow-operator#139]
Part of this epic https://github.com/stackabletech/issues/issues/241

### Acceptance criteria

- [ ] Resource requests and limits are configurable in CRD using the [common structs](https://github.com/stackabletech/operator-rs/blob/e56110dd394c98a67f21ff17f7fab6c88f3aa322/src/commons/resources.rs#L77) from operator-rs
- [ ] Resource requests and limits are configured for Kubernetes pods
- [ ] Resource requests and limits are configured in the product
- [ ] Adapt/Add integration tests to specify and test correct amount of resources
- [ ] Adapt/Add examples
- [ ] Adapt documentation: New section in `usage.adoc` with product specific information and link to common shared resources concept
- [ ] Optional: Use sensible defaults for each role (if reasonable and applicable) and document accordingly in `usage.adoc`
- [ ] Feature tracker updated

**Comment by lfrancke** [comment]
None of the boxes have been ticked. Can you please check if everything has been done?
I will update the feature tracker

**Comment by adwk67** [comment]
Sorry, didn't notice there was boxes here too :)
There's not much we can configure in the product as it is python so no easy way to set a memory limit (the other implementations are java where heap is set to x% of memory limit). I've added examples in the usage doc, but not as .yamls as there was talk of phasing them out and/or moving them to the documentation.

**Comment by lfrancke** [comment]
Great, thank you!
