### ISSUE TITLE
Evaluate ways to monitor Airflow and take decision on how to proceed

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/airflow-operator#25]
We'd like to have support to monitor Airflow using the Prometheus format.

I'd say that monitoring is important but for Airflow simple monitoring is fine for the beginning. We need to be able to tell whether the service is green/yellow/red. Everything beyond that is nice-to-have.

This ticket is a research ticket and the outcome should be a way forward (i.e. new tickets) on how to integrate Airflow with our existing Prometheus architecture.

I only googled briefly but it looks like Airflow provides metrics via [StatsD](https://github.com/statsd/statsd). It must be evaluated if a StatsD to Prometheus metrics exporter, like [statsd_exporter](https://github.com/prometheus/statsd_exporter), is a reasonable solution.

This is very similar in scope to the equivalent Superset issue: https://github.com/stackabletech/superset-operator/issues/13

Please also see https://github.com/stackabletech/airflow-operator/issues/15 which is about doing the Pod level changes

**Comment by adwk67** [comment]
There are at least three main ways to achieve this:

**1. use another component to visualize airflow metric e.g. celery + flower**

- example: [flower UI screenshots](https://flower.readthedocs.io/en/latest/screenshots.html)
- Pros
  - good integration with airflow (does not require any airflow plugins to be activated during installation)
- Cons
  - adds another monitoring tool
  - assumes that the `CeleryExecutor` is active
- Assessment
  - **reject**

**2. use airflow + statsd(-exporter) + prometheus**

- uses an interim component to receive metric data pushed from airflow and to map it to a prometheus-compatible format
- Pros
  - is a well-documented route: a plugin has to be applied to activate/include the `statsd` - see examples/information [here](https://github.com/riodpp/airflow-metrics-monitoring/blob/main/docker-compose.yaml) and [here](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#environment-variables-supported-by-docker-compose)
- Cons
  - extra components needed (airflow plugin, statsd server) as well as config changes
- Assessment
  - **consider**

**3. use a prometheus plugin e.g. airflow-exporter** 

- similar to 2. above
- Pros
  - a more streamlined version of statsd-exporter (the plugin exposes the prometheus end point directly)
- Cons
  - more of an unknown quantity (small community, not officially documented by airflow)
- Assessment
  - **consider**

**Comment by adwk67** [comment]
Output from 3. above (airflow-exporter) at e.g. http://172.19.0.10:32105/admin/metrics/:

```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 19225.0
python_gc_objects_collected_total{generation="1"} 7669.0
python_gc_objects_collected_total{generation="2"} 423.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 994.0
python_gc_collections_total{generation="1"} 90.0
python_gc_collections_total{generation="2"} 7.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="12",version="3.8.12"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 8.10090496e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.48303616e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.64447363946e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 5.859999999999999
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 13.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP airflow_dag_status Shows the number of dag starts with this status
# TYPE airflow_dag_status gauge
airflow_dag_status{dag_id="example_complex",owner="airflow",status="running"} 1.0
airflow_dag_status{dag_id="example_complex",owner="airflow",status="success"} 1.0
airflow_dag_status{dag_id="example_bash_operator",owner="airflow",status="success"} 5.0
# HELP airflow_dag_last_status Shows the status of last dagrun
# TYPE airflow_dag_last_status gauge
airflow_dag_last_status{dag_id="example_complex",owner="airflow",status="queued"} 0.0
airflow_dag_last_status{dag_id="example_complex",owner="airflow",status="success"} 0.0
airflow_dag_last_status{dag_id="example_complex",owner="airflow",status="running"} 1.0
airflow_dag_last_status{dag_id="example_complex",owner="airflow",status="failed"} 0.0
airflow_dag_last_status{dag_id="example_bash_operator",owner="airflow",status="queued"} 0.0
airflow_dag_last_status{dag_id="example_bash_operator",owner="airflow",status="success"} 1.0
airflow_dag_last_status{dag_id="example_bash_operator",owner="airflow",status="running"} 0.0
airflow_dag_last_status{dag_id="example_bash_operator",owner="airflow",status="failed"} 0.0
# HELP airflow_dag_run_duration Maximum duration of currently running dag_runs for each DAG in seconds
# TYPE airflow_dag_run_duration gauge
airflow_dag_run_duration{dag_id="example_complex"} 12.0
# HELP airflow_task_status Shows the number of task starts with this status
# TYPE airflow_task_status gauge
airflow_task_status{dag_id="example_bash_operator",owner="airflow",status="success",task_id="runme_2"} 5.0
airflow_task_status{dag_id="example_bash_operator",owner="airflow",status="success",task_id="runme_0"} 5.0
airflow_task_status{dag_id="example_bash_operator",owner="airflow",status="success",task_id="runme_1"} 5.0
airflow_task_status{dag_id="example_bash_operator",owner="airflow",status="skipped",task_id="run_this_last"} 5.0
...
```

**Comment by siegfriedweber** [comment]
We decided in the backlog refinement meeting to implement option 2 (using statsd-exporter).

Follow-up ticket: #15
