### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by fhennig** [stackabletech/airflow-operator#337]
https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#web-authentication

https://flask-appbuilder.readthedocs.io/en/latest/security.html

## Issue checklist

This is a simple checklist of things to bear in mind when creating a new issue.

- [ ] Describe the use-case, as far is possible. For instance, using the pattern "As a XXXX, I would like XXXX to be able to do XXXX" helps to identify the feature as well as the problem it is intended to address.
- [ ] Indicate an approximate level of importance and urgency.
- [ ] Indicate if there is a known work-around until such time as the issue has been implemented.

**Comment by Maleware** [comment]
We could argue this is done with a 60% solution already with https://github.com/stackabletech/airflow-operator/pull/493 being merged.

We *could* similar to [superset](https://github.com/stackabletech/docker-images/blob/main/superset/Dockerfile#L66) add the necessary libraries to our dockerfile. However those could be installed via the mechanism mentioned above too.

**Comment by Maleware** [comment]
https://github.com/stackabletech/docker-images/pull/891 will make it a 80 percent solution

**Comment by adwk67** [comment]
We added a comment here: https://github.com/stackabletech/airflow-operator/pull/524#issuecomment-2450114167

**Comment by lfrancke** [comment]
Thank you! Do we have docs for this?

**Comment by adwk67** [comment]
Docs are [here](https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/airflow/pages/usage-guide/security.adoc#openid-connect) and [here](https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/airflow/pages/usage-guide/security.adoc#openid-connect-1).
