### ISSUE TITLE
[NEW VERSION] Airflow 2.9.2

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#448]
**Which new version of Apache Airflow should we support?**

2.9.2

**Additional information**

Changelog:

[Release notes](https://airflow.apache.org/docs/apache-airflow/2.9.2/release_notes.html)

**Changes required (2.9.1)**

- [remove](https://airflow.apache.org/docs/apache-airflow/2.9.1/release_notes.html) SQL Server as a supported backend (remove the provider for the image)
- [support](https://airflow.apache.org/docs/apache-airflow/2.9.1/release_notes.html) Python 3.12

**Changes required (2.8.3)**

- [support](https://github.com/apache/airflow/pull/37713) SMTP provider is automatically installed (changes needed to the contraints file?)

Are there any upstream changes that we need to support?
e.g. new features, changed features, deprecated features etc.

**New features**

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by maltesander** [comment]
added in https://github.com/stackabletech/docker-images/pull/762
