### ISSUE TITLE
Refactor airflow init process

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#50]
### Affected version

All versions

### Current and expected behavior

On start-up the airflow webserver is not marked as ready until its port is reachable; the other (non-service) components do not have a probe applied. This results in the stateful set being marked as available before the database has been correctly initialised.

Correct behaviour should be: all components should wait until the airflow database has been correctly initialised (adding an admin user etc.) and then and only then marked as ready. This will avoid having multiple restarts.

### Possible solution

The Airflow database is initialised by an `Init` job that calls the airflow database commands. Other commands (`airflow db check`, `airflow db check-migrations`) can be sued to confirm that the database is ready and reachable: these should be implemented as readiness probes.

**Comment by adwk67** [comment]
I've given this some thought and I think there are at least three ways forward:

1. #### Change nothing

- we change nothing and let Kubernetes' eventual-consistency do its thing. If we reconcile all the elements together - the secret, the cluster and the `Init` job, like we do for the unit test - then we have a couple of restarts of the scheduler, and that's all (the integration test was "worse" than it had to be as the `Init` job was not started simultaneously, but rather in a subsequent stage). Starting a single cluster + `Init` job on its owns yields the following for a typical run:
  - 0-20s: `Init` job runs
  - 0-35s: Scheduler restarts twice as it can connect to the (postgres) database defined in the secret but finds no Admin user there until the init job is complete, when it can itself complete
  - 35s+: everything stable

2. #### Make the `Init` job independent of the cluster

- the `Init` job currently has a reference to the airflow cluster: this is used to access and use the same version of the airflow image.
- this dependency can be removed by giving the version directly and replacing this:
```
----
-apiVersion: command.airflow.stackable.tech/v1alpha1
-kind: Init
-metadata:
-  name: airflow-cluster-command-init
-spec:
-  clusterRef:
-    name: airflow
-  credentialsSecret: simple-airflow-credentials
```
with e.g. this:
```
---
apiVersion: command.airflow.stackable.tech/v1alpha1
kind: Init
metadata:
  name: airflow-cluster-command-init
spec:
  version: 2.2.3-python38
  credentialsSecret: simple-airflow-credentials
```
- this means we have the option of starting the `Init` job first, thus avoiding any restarts (although we can still start them simultaneously if we want to)

3. #### Implement a readiness probe based on the database contents

- this approach would involve not just checking the database connection (which can easily done by calling `airflow db check` on one of the airflow pods), but also querying if the expected user exists
- this is not possible using the airflow CLI: there is no command such as `airflow db users list`. There is access to the database shell, but this requires:
  - that the necessary shell tools (and not *just* the airflow libraries used for connectivity) are present on the image, and
  - there is an implementation for each supported database

4. #### Implement a readiness probe based on parsing the results of `airflow db init`

- this does not rely on anything other than airflow CLI commands, though we are making assumptions about the returned value.

Of these, 3 is the most implementation effort and 3 & 4 are both somewhat fragile as they depend on internal details. 
2 is easy to implement but breaks the link between cluster and `Init` job, although arguably the secret is a harder dependency as that determines where the database is that is being updated.

**Comment by lfrancke** [comment]
I'm late to this but: Why do we have a separate `Init` thing in the first place?
Why is this not part of the AirflowCluster object itself?

**Comment by adwk67** [comment]
We only want the `Init` step to run once and not to be re-started automatically.

**Comment by lfrancke** [comment]
Yeah, but that should be the job of the operator to check (which goes right back to the core of this ticket)
The `Init` is an imperative command which doesn't fit the declarative Kubernetes model very well.

So I think a bigger refactor might be what I'm leaning towards.

**Comment by adwk67** [comment]
Yes, looking at the superset operator (upon which this was based) we have refactored that in the meantime.

**Comment by adwk67** [comment]
We could refactor it similar to what we did here: https://github.com/stackabletech/superset-operator/pull/71:-

"This change allows us to also depend on the DB being ready (or not). This is necessary for writing the druid connection information into the DB."
