### ISSUE TITLE
Operator can't be installed on OpenShift 4.16+

### ISSUE THREAD

**Issue by Nabsku** [stackabletech/airflow-operator#566]
### Affected Stackable version

Any

### Affected Apache Airflow version

Any

### Current and expected behavior

We've recently updated two of our clusters which have the operators for `airflow` `commons` `secret` running and after upgrading we've noticed that they can't find their respective operator definitions in the certified-operators hub. 

On other clusters I've noticed that we can't install those same operators on clusters above 4.16. 

On the RedHat catalog site, under `Deploy & use` it says that OpenShift up to and including 4.17 is supported..

Is this just an issue on our end? 

Kind Regards

### Environment

Output of oc version:
```Client Version: 4.17.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.16.25
Kubernetes Version: v1.29.10+67d3387
```

### Would you like to work on fixing this bug?

None

**Comment by adwk67** [comment]
@Nabsku thanks for opening this ticket! The last certification was done against 4.15, so there won't be anything showing up in certified-operators for 4.16 just yet. We are planning to do that in the new year, possibly in January.

**Comment by Nabsku** [comment]
That sounds like a plan. We will use Helm/stackablectl in the meantime. Thanks for the great software!
