### ISSUE TITLE
Evaluate astronomer.io

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#67]
### Summary
As a user I want to understand the benefits and limitations of [Astro](https://www.astronomer.io/), specifically the features which highlight potential extension/enhancement of the airflow operator.

### Background
Astro(nomer) is a proprietary orchestration framework powered by airflow. It splits the workflow architecture into a control plane hosted by Astronomer (UI, user & environment management) and a data plane (company data) hosted by the client. 

### Scope
This is a research ticket which will cover/answer the following:
- how is astro used in conjunction with kubernetes? Can it run within kubernetes or does its KubernetesPodOperator only deploy jobs to kubernetes from outside the cluster?
- what UI/management features does Astro offer that extend the Airflow UI?
- how does security work? Is it extensible?

**Comment by lfrancke** [comment]
Thank you!  I only had a single question and put it in the document. I'll close this issue.
