### ISSUE TITLE
Handle stale information/clean up stale resources

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/airflow-operator#72]
Currently our operators will not act on removed information from the CR in some/most/all cases.

One example:
HBase operator has three roles (master, regionServer, restServer). If I create a HBase server CR with a restServer component and then remove it later (entirely, not setting replicas to 0) our operator will not clean up the STS that belongs to this role.

## Proposed solution

Since operator-rs 0.24.0 there is a `ClusterResource` struct which is used to find and track Kubernetes resources belonging to a Cluster object. An example of its usage can be found in the Superset Operator: https://github.com/stackabletech/superset-operator/blob/main/rust/operator-binary/src/superset_controller.rs#L241

## Acceptance criteria

- [x] This is done when all stale Kubernetes resources are cleaned up. A resource becomes stale when it's not part of the current cluster definition anymore.
- [x] The `AirflowDB` resource is excluded from this recycling process.
- [x] Also referenced `ConfigMaps` and `PersistenVolumeClaims` are not deleted.
- [x] There is at least one test.
- [ ] Documentation on operator implementation is updated with information regarding handling of stale resources.
- [x] Upgrade to the latest `operator-rs` version (`0.25` at the moment)

NOTE: This is part of an epic (https://github.com/stackabletech/issues/issues/203) and _might_ not apply to this operator. If that is the case please comment on this issue and just close it. This issue was created as part of a special bulk creation operation.

**Comment by fhennig** [comment]
I think documenting this could just be a sentence in a more general "how the operator works" documentation page, which we do not have right now. I'll defer this to this ticket: https://github.com/stackabletech/documentation/issues/282
