### ISSUE TITLE
[NEW VERSION] 2.4.1

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#86]
**Which new version of Apache Airflow should we support?**

2.4.1

**Additional information**

The release notes are [here](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-4-0-2022-09-19).

**Changes / Additions**

In the scope of this ticket:

- check that tests, getting started scripts, documentation and demos work with the new version
- have a look at the items below from the release notes and create new issues for things which merit further work (e.g. making use of the new 2.4.0 data scheduling feature in a `stackablectl` demo)

From the release notes:-
- 2.4.1
  - Only bug fixes 
- 2.4.0
  - [data-aware scheduling](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#data-aware-scheduling-and-dataset-concept-added-to-airflow) 
  - [multiple dag-processors](https://github.com/apache/airflow/pull/25935)
- 2.3.3
  - Flask App Builder was upgraded to the  [major version 4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#we-ve-upgraded-flask-app-builder-to-a-major-version-4-24399)
- 2.3.0 
  - [auth-backends-replaces-auth-backend-configuration-setting](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#auth-backends-replaces-auth-backend-configuration-setting-21472)
  - [auth-backends-includes-session](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#auth-backends-includes-session-21640)
  - preparation for multi-tenancy: [option to separate dag-processor from scheduler](https://github.com/apache/airflow/pull/22305)
  - [add users in LDAP mode](https://github.com/apache/airflow/pull/22619)
  - [LocalKubernetesExecutor](https://github.com/apache/airflow/issues/16185)
  - [Change default auth backend](https://github.com/apache/airflow/pull/21640)

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [x] Update the Docker image
- [x] Update documentation to include supported version(s)
- [ ] Update operator to support the new version (if needed)
- [x] Update integration tests to test use the new versions (in addition or replacing old versions
- [x] Update examples to use new versions

**Comment by razvan** [comment]
This introduces a new major dependency version (5.2.2) for [apache-airflow-providers-postgres](https://pypi.org/project/apache-airflow-providers-postgres/5.2.2/) which unlike the previous version we had (4.1.0), depends on `psycopg2` instead of `psycopg2-binary`. 

This means the Airflow image now has to include the Posgresql client programs and the `libpq` library as described [here](https://www.psycopg.org/docs/install.html#build-prerequisites).
